local wezterm = require 'wezterm'
local act = wezterm.action

return {
  -- { key = 'Enter',      mods = 'ALT',            action = act.ToggleFullScreen },
  { key = 'phys:Space', mods = 'SHIFT|CTRL',     action = act.QuickSelect },
  { key = 'Tab',        mods = 'SHIFT|CTRL',     action = act.ActivateTabRelative(-1) },
  { key = 'Tab',        mods = 'CTRL',           action = act.ActivateTabRelative(1) },
  { key = 'h',          mods = 'CTRL|ALT',       action = act.ActivateTabRelative(-1) },
  { key = 'l',          mods = 'CTRL|ALT',       action = act.ActivateTabRelative(1) },
  { key = 'v',          mods = 'ALT',            action = act.SplitVertical { domain = 'CurrentPaneDomain' } },
  { key = 'v',          mods = 'CTRL|ALT',       action = act.SplitVertical { domain = 'CurrentPaneDomain' } },
  { key = 's',          mods = 'ALT',            action = act.SplitHorizontal { domain = 'CurrentPaneDomain' } },
  { key = 's',          mods = 'CTRL|ALT',       action = act.SplitHorizontal { domain = 'CurrentPaneDomain' } },
  { key = ')',          mods = 'SHIFT|CTRL',     action = act.ResetFontSize },
  { key = '+',          mods = 'SHIFT|CTRL',     action = act.IncreaseFontSize },
  { key = '-',          mods = 'SHIFT|CTRL',     action = act.DecreaseFontSize },
  { key = '1',          mods = 'CTRL|ALT',       action = act.ActivateTab(0) },
  { key = '2',          mods = 'CTRL|ALT',       action = act.ActivateTab(1) },
  { key = '3',          mods = 'CTRL|ALT',       action = act.ActivateTab(2) },
  { key = '4',          mods = 'CTRL|ALT',       action = act.ActivateTab(3) },
  { key = '5',          mods = 'CTRL|ALT',       action = act.ActivateTab(4) },
  { key = '6',          mods = 'CTRL|ALT',       action = act.ActivateTab(5) },
  { key = '7',          mods = 'CTRL|ALT',       action = act.ActivateTab(6) },
  { key = '8',          mods = 'CTRL|ALT',       action = act.ActivateTab(7) },
  { key = '9',          mods = 'CTRL|ALT',       action = act.ActivateTab(8) },
  { key = 'h',          mods = 'CTRL',           action = act.ActivatePaneDirection 'Left' },
  { key = 'j',          mods = 'CTRL',           action = act.ActivatePaneDirection 'Down' },
  { key = 'k',          mods = 'CTRL',           action = act.ActivatePaneDirection 'Up' },
  { key = 'l',          mods = 'CTRL',           action = act.ActivatePaneDirection 'Right' },
  { key = 'LeftArrow',  mods = 'CTRL|ALT',       action = act.AdjustPaneSize { 'Left', 4 } },
  { key = 'RightArrow', mods = 'CTRL|ALT',       action = act.AdjustPaneSize { 'Right', 4 } },
  { key = 'UpArrow',    mods = 'CTRL|ALT',       action = act.AdjustPaneSize { 'Up', 2 } },
  { key = 'DownArrow',  mods = 'CTRL|ALT',       action = act.AdjustPaneSize { 'Down', 2 } },
  { key = 'C',          mods = 'SHIFT|CTRL',     action = act.CopyTo 'Clipboard' },
  { key = 'V',          mods = 'SHIFT|CTRL',     action = act.PasteFrom 'Clipboard' },
  { key = 'F',          mods = 'SHIFT|CTRL',     action = act.Search 'CurrentSelectionOrEmptyString' },
  { key = 'K',          mods = 'SHIFT|CTRL',     action = act.ClearScrollback 'ScrollbackOnly' },
  { key = 'L',          mods = 'SHIFT|CTRL|ALT', action = act.ShowDebugOverlay },
  { key = 'N',          mods = 'SHIFT|CTRL',     action = act.SpawnWindow },
  { key = 'P',          mods = 'SHIFT|CTRL',     action = act.ActivateCommandPalette },
  { key = 'R',          mods = 'SHIFT|CTRL|ALT', action = act.ReloadConfiguration },
  { key = 'T',          mods = 'SHIFT|CTRL',     action = act.SpawnTab 'CurrentPaneDomain' },
  { key = 'W',          mods = 'SHIFT|CTRL',     action = act.CloseCurrentTab { confirm = true } },
  { key = 'M',          mods = 'SHIFT|CTRL',     action = act.TogglePaneZoomState },
  { key = 'Z',          mods = 'SHIFT|CTRL',     action = act.TogglePaneZoomState },
  { key = 'q',          mods = 'ALT',            action = act.CloseCurrentPane { confirm = true } },
  { key = 'q',          mods = 'CTRL|ALT',       action = act.CloseCurrentPane { confirm = true } },
  { key = 'u',          mods = 'CTRL|ALT',       action = act.ScrollByPage(-0.5) },
  { key = 'd',          mods = 'CTRL|ALT',       action = act.ScrollByPage(0.5) },
  { key = 'PageUp',     mods = 'SHIFT',          action = act.ScrollByPage(-1) },
  { key = 'PageDown',   mods = 'SHIFT',          action = act.ScrollByPage(1) },
  { key = 'Copy',       mods = 'NONE',           action = act.CopyTo 'Clipboard' },
  { key = 'Paste',      mods = 'NONE',           action = act.PasteFrom 'Clipboard' },

  -- modes
  { key = 'X',          mods = 'SHIFT|CTRL',     action = act.ActivateCopyMode },
  { key = 'w',          mods = 'CTRL|ALT',       action = act.ActivateKeyTable { name = 'create_pane_mode', timeout_milliseconds = 2000, } },
  { key = 'w',          mods = 'LEADER',         action = act.ActivateKeyTable { name = 'create_pane_mode', timeout_milliseconds = 2000, } },
  { key = 'r',          mods = 'LEADER',         action = act.ActivateKeyTable { name = 'resize_pane_mode', one_shot = false, }, }
}
